In [1]:
import numpy as np
import pandas as pd

In [18]:
def projectRollerWidth(df,rollerWidth=6, nPoints=6):
        copyDF = df.copy()
        halfWidth = rollerWidth // 2
        for i in np.arange(-halfWidth, halfWidth, rollerWidth / nPoints):
            tmpDF = copyDF.copy()
            tmpDF.latitude = (
                np.sin(2 * np.pi / 360 * (copyDF.heading.values - 90)) * i / 3600 / 101
                + copyDF.latitude.values
            )
            tmpDF.longitude = (
                np.cos(2 * np.pi / 360 * (copyDF.heading.values - 90)) * i / 3600 / 80
                + copyDF.longitude.values
            )
            tmpDF.original = False
            df = df.append(tmpDF)
        df = df.sort_values("time")
        return df

In [19]:
# def projectRollerWidth(df,rollerWidth=6, nPoints=6):
#         copyDF = df.copy(deep=True)
#         copyDF1=df.copy(deep=True)
#         halfWidth = rollerWidth // 2
#         for i in np.arange(-halfWidth, halfWidth, rollerWidth / nPoints):
#             tmpDF = copyDF1.copy()
#             tmpDF.latitude = (
#                 np.sin(2 * np.pi / 360 * (copyDF1.heading.values - 90)) * i / 3600 / 101
#                 + copyDF.latitude.values
#             )
#             tmpDF.longitude = (
#                 np.cos(2 * np.pi / 360 * (copyDF1.heading.values - 90)) * i / 3600 / 80
#                 + copyDF.longitude.values
#             )
#             print(tmpDF.head())
#             tmpDF.original = False
#             copyDF = copyDF.append(tmpDF)
#         copyDF = copyDF.sort_values("time")
#         return copyDF

In [23]:
df=pd.read_csv("/home/shankar/Documents/processed_elk_3_to_4_sep_14.csv")
df

,name,time,density,heading,latitude,longitude,passID,speed,temperature
0,processed,2022-09-14T22:00:00.075Z,91.00,3.386,38.392346,-121.353017,228,3.245,30.836490
1,processed,2022-09-14T22:00:00.203Z,93.89,3.386,38.392346,-121.353017,228,3.245,30.834741
2,processed,2022-09-14T22:00:00.331Z,88.72,3.386,38.392346,-121.353017,228,3.245,30.849612
3,processed,2022-09-14T22:00:00.459Z,93.89,3.386,38.392346,-121.353017,228,3.245,30.850195
4,processed,2022-09-14T22:00:00.587Z,91.00,3.386,38.392346,-121.353017,228,3.245,30.835907
...,...,...,...,...,...,...,...,...,...
28120,processed,2022-09-14T22:59:59.435Z,88.01,0.000,38.385558,-121.350302,310,0.046,30.453034
28121,processed,2022-09-14T22:59:59.563Z,88.01,0.000,38.385558,-121.350302,310,0.046,30.456825
28122,processed,2022-09-14T22:59:59.691Z,88.01,0.000,38.385558,-121.350302,310,0.046,30.459158
28123,processed,2022-09-14T22:59:59.819Z,88.01,0.000,38.385558,-121.350302,310,0.046,30.460908
28124,processed,2022-09-14T22:59:59.947Z,88.01,0.000,38.385558,-121.350302,310,0.081,30.458283

In [21]:
df_projected=projectRollerWidth(df)

/tmp/ipykernel_1171908/134976459.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(tmpDF)
/tmp/ipykernel_1171908/134976459.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(tmpDF)
/tmp/ipykernel_1171908/134976459.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(tmpDF)
/tmp/ipykernel_1171908/134976459.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(tmpDF)
/tmp/ipykernel_1171908/134976459.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(tmpDF)

In [22]:
df_projected

,name,time,density,heading,latitude,longitude,passID,speed,temperature
0,processed,2022-09-14T22:00:00.075Z,91.00,3.386,38.392346,-121.353017,228,3.245,30.836490
0,processed,2022-09-14T22:00:00.075Z,91.00,3.386,38.392346,-121.353017,228,3.245,30.836490
0,processed,2022-09-14T22:00:00.075Z,91.00,3.386,38.392349,-121.353017,228,3.245,30.836490
0,processed,2022-09-14T22:00:00.075Z,91.00,3.386,38.392343,-121.353017,228,3.245,30.836490
0,processed,2022-09-14T22:00:00.075Z,91.00,3.386,38.392351,-121.353017,228,3.245,30.836490
...,...,...,...,...,...,...,...,...,...
28124,processed,2022-09-14T22:59:59.947Z,88.01,0.000,38.385564,-121.350302,310,0.081,30.458283
28124,processed,2022-09-14T22:59:59.947Z,88.01,0.000,38.385566,-121.350302,310,0.081,30.458283
28124,processed,2022-09-14T22:59:59.947Z,88.01,0.000,38.385558,-121.350302,310,0.081,30.458283
28124,processed,2022-09-14T22:59:59.947Z,88.01,0.000,38.385555,-121.350302,310,0.081,30.458283
28124,processed,2022-09-14T22:59:59.947Z,88.01,0.000,38.385552,-121.350302,310,0.081,30.458283